version: "3"

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-scheduler-data:/data
    command: redis-server

  bot:
    build: .
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis

volumes:
  redis-scheduler-data:
